spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db:5432/hubify}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
spring.mvc.cors.allowed-origins=${ALLOWED_ORIGINS:*}
spring.mvc.cors.allowed-methods=*

# HikariCP Connection Pool Configs
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

# Aumentar o limite para suportar imagens Base64 no perfil
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-post-size=10MB
server.tomcat.max-swallow-size=10MB
