spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db:5432/hubify}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8081}
spring.mvc.cors.allowed-origins=${ALLOWED_ORIGINS:*}
spring.mvc.cors.allowed-methods=*
