spring:
  application:
    name: backend

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/hubify}
    username: ${DB_USERNAME:hubifyuser}
    password: ${DB_PASSWORD:hubifypassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

hubify:
  upload-dir: uploads

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 1 day in ms
